_wandb:
    value:
        cli_version: 0.23.1
        e:
            auhtbqlfasddr3vdafws0yf9avuci9d5:
                codePath: e:\SEMESTER 5\DEEP LEARNING\FINAL\neurips-open-polymer-prediction-2025\src\main3.ipynb
                codePathLocal: main3.ipynb
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "512092008448"
                        used: "480240345088"
                email: benedictuserwdev@gmail.com
                executable: d:\anaconda\envs\dl_env\python.exe
                git:
                    commit: f297689376e06c52b862b95f0ada83ee76fc2f2b
                    remote: https://github.com/Erwdev/FINAL-DEEP-LEARNING.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-9c52fee2-6965-cac3-f167-ba06cef45f1f
                host: LAPTOP-HDSBD60C
                memory:
                    total: "12578578432"
                os: Windows-10-10.0.26100-SP0
                program: e:\SEMESTER 5\DEEP LEARNING\FINAL\neurips-open-polymer-prediction-2025\src\main3.ipynb
                python: CPython 3.10.18
                root: e:\SEMESTER 5\DEEP LEARNING\FINAL\neurips-open-polymer-prediction-2025\src
                startedAt: "2025-12-04T15:44:23.055898Z"
                writerId: auhtbqlfasddr3vdafws0yf9avuci9d5
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
                - 77
            "2":
                - 1
                - 5
                - 6
                - 53
                - 77
            "3":
                - 1
                - 2
                - 3
                - 13
                - 15
                - 16
                - 62
            "4": 3.10.18
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: PolymerGNN
batch_size:
    value: 128
dropout:
    value: 0.2
embedding_dim:
    value: 10
hidden_dim:
    value: 64
learning_rate:
    value: 0.001
loss_function:
    value: masked_mse
num_epochs:
    value: 100
num_node_features:
    value: 5
num_outputs:
    value: 5
optimizer:
    value: Adam
scheduler:
    value: ReduceLROnPlateau
target_columns:
    value:
        - Tg
        - FFV
        - Tc
        - Density
        - Rg
train_split:
    value: 0.8
